### ISSUE TITLE
API issue

### ISSUE THREAD

**Issue by quentinglorieux** [bryantgillespie/nuxt3-directus-starter#12]
Hi 
I struggle to make the API call in the ExamplesApiRoutes to work.
the sayHello function doesnt work with a dynamic name.value using v-bind but it does with a static param (see bellow) 

```
async function sayHello() {
  const { data } = await useFetch('/api/hello', {
    params: {
       name: name.value,
      //name: 'quentin', this works but name.value doesnt ?
    },
  })
  response.value = data.value
  loading.value = false
}
```

Maybe it comes from the useQuery in the hello.js file ?   
```

const query = useQuery(event)
  return {
    message: `Hello ${query.name} 👋`,
  }
})
```

Any idea ?

**Comment by bryantgillespie** [comment]
Yes. It looks like I goofed up. 

I think this bit in the Vue component 
``` vue
response.value = data.value
```

Should be this
``` vue
response.value = data
```
Because the response coming back from the API is obviously not reactive.

Try that and let me know if that doesn't solve it. 

I did a quick fix here.
https://github.com/bryantgillespie/nuxt3-directus-starter/commit/47bd5210250e833ef47f9ed165a782eb83b66df8

**Comment by bryantgillespie** [comment]
Let me test this

**Comment by bryantgillespie** [comment]
Check out this commit and see if that doesn't solve it for you
https://github.com/bryantgillespie/nuxt3-directus-starter/commit/250328265d903bb4ae17628225f246d588bb68b0

**Comment by quentinglorieux** [comment]
Great, didnt know about the cache issue.
Thx
Q

**Comment by quentinglorieux** [comment]
Just a related question.
Let's say  I have opened a slug page after fetching with the content compoment.
The if I reload the slug page I obtain an error 500
`
Cannot read property 'title' of null
at processTicksAndRejections (internal/process/task_queues.js:95:5)`

I dont get why we loose the property ?

**Comment by bryantgillespie** [comment]
> Just a related question. Let's say I have opened a slug page after fetching with the content compoment. The if I reload the slug page I obtain an error 500 ` Cannot read property 'title' of null at processTicksAndRejections (internal/process/task_queues.js:95:5)`
> 
> I dont get why we loose the property ?

Looks like I need to do some updates. 
I think this is probably because I updated this to the latest RC

Found this on their documentation.
https://v3.nuxtjs.org/bridge/bridge-composition-api#usemeta

Looks like useMeta is now deprecated.

Should probably be using the [useHead](https://v3.nuxtjs.org/getting-started/seo-meta#composable-usehead) composable instead.

```vue
useMeta({
  title: page.value.title,
})
```

should be
```vue
useHead({
  title: page.value.title,
})
```

**Comment by staminna** [comment]
I amended to useHead and I can read fine in Postman the GET request, but in the either Safari or Brave I get:

<img width="1211" alt="Captura de ecrã 2022-11-16, às 23 52 46" src="https://user-images.githubusercontent.com/515180/202320285-7532ad1d-697a-47d3-8422-f3976b9772ad.png">

<img width="574" alt="Captura de ecrã 2022-11-16, às 23 57 40" src="https://user-images.githubusercontent.com/515180/202320678-6ff7a72d-bf22-441b-be73-f335ebdd59c4.png">

The database is already on AWS RDS but it shouldn't be the case
It is public file and role but I am authenticated successfully and everything else is working.

**Comment by bryantgillespie** [comment]
The error you're seeing there is coming back from your Directus instance. So there's likely something wrong with your call to the Directus API or the permissions aren't set correctly on your Directus instance.

**Comment by quentinglorieux** [comment]
> Looks like useMeta is now deprecated.
> 
> Should probably be using the [useHead](https://v3.nuxtjs.org/getting-started/seo-meta#composable-usehead) composable instead.
> 
> ```
> useMeta({
>   title: page.value.title,
> })
> ```
> 
> should be
> 
> ```
> useHead({
>   title: page.value.title,
> })
> ```

It was indeed deprecated but I still have the same issue. I think its more related to the fetching method.

<img width="1157" alt="Screenshot 2022-11-17 at 16 40 46" src="https://user-images.githubusercontent.com/16529637/202490999-b8133b5d-7b3f-479d-977f-10e646067a01.png">

Error I have: 
```
[Vue warn]: Unhandled error during execution of setup function 
  at <[slug] onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< undefined > >
```

**Comment by staminna** [comment]
> The error you're seeing there is coming back from your Directus instance. So there's likely something wrong with your call to the Directus API or the permissions aren't set correctly on your Directus instance.

I am using unmodified Docker Image on my localhost and set read permissions for Pages, Images and the next one right  bellow.
I also did not change the code on the call  or any other part from your repository.

**Comment by bryantgillespie** [comment]
> I am using unmodified Docker Image on my localhost and set read permissions for Pages, Images and the next one right  bellow.
> I also did not change the code on the call  or any other part from your repository.
> 
Then it sounds like there may be an issue with the way I'm making the call to the API then.

I'll investigate further but will be a few days before I have time to dive into it.

**Comment by BlackDahlia313** [comment]
> > I am using unmodified Docker Image on my localhost and set read permissions for Pages, Images and the next one right  bellow.
> > I also did not change the code on the call  or any other part from your repository.
> 
> Then it sounds like there may be an issue with the way I'm making the call to the API then.
> 
> I'll investigate further but will be a few days before I have time to dive into it.

https://github.com/bryantgillespie/nuxt3-directus-starter/pull/24

:)
