### ISSUE TITLE
yarn dev run into error (fresh setup)

### ISSUE THREAD

**Issue by NatsuDragneelKl** [bryantgillespie/nuxt3-directus-starter#19]
If I set SSR to false it work.

Can someone give me a tipp?

Error:
`
[Vue warn]: inject() can only be used inside setup() or functional components.                                15:19:15
[Vue warn]: Server rendering context not provided. Make sure to only call useSSRContext() conditionally in the server build.
[Vue warn]: Unhandled error during execution of setup function                                                15:19:15
  at <NuxtRoot>
[nuxt] [request error] [unhandled] [500] Cannot read properties of undefined (reading 'modules')              15:19:15
  at _sfc_main.setup (c:\NuxtProject\node_modules\nuxt\dist\app\components\nuxt-root.vue:80:16)
  at callWithErrorHandling (c:\NuxtProject\node_modules\@vue\runtime-core\dist\runtime-core.cjs.js:171:22)
  at setupStatefulComponent (c:\NuxtProject\node_modules\@vue\runtime-core\dist\runtime-core.cjs.js:7194:29)
  at setupComponent (c:\NuxtProject\node_modules\@vue\runtime-core\dist\runtime-core.cjs.js:7149:11)
  at renderComponentVNode (c:\NuxtProject\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:628:17)
  at renderToString (c:\NuxtProject\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:906:26)
  at Object.renderToString$1 [as renderToString] (/C:/xampp816/htdocs/volkssolidaritaet-jobportal/.nuxt/dev/index.mjs:664:24)
  at Object.renderToString (/C:/xampp816/htdocs/volkssolidaritaet-jobportal/node_modules/vue-bundle-renderer/dist/runtime.mjs:173:40)
  at runMicrotasks (<anonymous>)
  at processTicksAndRejections (node:internal/process/task_queues:96:5)
[Vue warn]: inject() can only be used inside setup() or functional components.                                15:19:15
[Vue warn]: Server rendering context not provided. Make sure to only call useSSRContext() conditionally in the server build.
[Vue warn]: Unhandled error during execution of setup function                                                15:19:15
  at <NuxtRoot>
[nuxt] [request error] [unhandled] [500] Cannot read properties of undefined (reading 'modules')              15:19:15
  at _sfc_main.setup (c:\NuxtProject\node_modules\nuxt\dist\app\components\nuxt-root.vue:80:16)
  at callWithErrorHandling (c:\NuxtProject\node_modules\@vue\runtime-core\dist\runtime-core.cjs.js:171:22)
  at setupStatefulComponent (c:\NuxtProject\node_modules\@vue\runtime-core\dist\runtime-core.cjs.js:7194:29)                                                                                          15:18:11
  at setupComponent (c:\NuxtProject\node_modules\@vue\runtime-core\dist\runtime-core.cjs.js:7149:11)
  at renderComponentVNode (c:\NuxtProject\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:628:17)
  at renderToString (c:\NuxtProject\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:906:26)
  at Object.renderToString$1 [as renderToString] (/C:/xampp816/htdocs/volkssolidaritaet-jobportal/.nuxt/dev/index.mjs:664:24)
  at Object.renderToString (/C:/NuxtProject/node_modules/vue-bundle-renderer/dist/runtime.mjs:173:40)
  at runMicrotasks (<anonymous>)
  at processTicksAndRejections (node:internal/process/task_queues:96:5)

`

**Comment by Loosie94** [comment]
You should provide more info and code to help you further. 
Also, as one of your error message says: "inject() can only be used inside setup()" you should use this function inside the <script setup> line, or with the setup() in the export function. Also, check if you have client compontent. Then wrap a <ClientOnly> tag around them. Maybe this helps. See: https://nuxt.com/docs/api/components/client-only#clientonly

**Comment by NeekoGta** [comment]
I encountered the same issue just right now.

**No changes in the code**, only using this template, `yarn install` & `yarn dev` and getting the same error than @NatsuDragneelKl

**Comment by NatsuDragneelKl** [comment]
I don't know where the error is, I dont touch any file. As NeekoDev said this happens on fresh project

**Comment by NatsuDragneelKl** [comment]
@NeekoDev I upgradet Nuxt (with npx nuxi upgrade) to version 3.3.1 and now it seems to work ;)

**Comment by bryantgillespie** [comment]
Closing this guy because I think it was a Nuxt specific issue.
